theme: jekyll-theme-architect
title: Eat Anywhere
description: "Make new friends, try new foods, discover your neighborhood"
url: "http://terrib1e.github.io/eata"
author: EC
google_analytics: UA-101230746-1

#social
linkedin: https://linkedin.com/
github: https://github.com/Terrib1e
email: mailto:niftyme@protonmail.com